name: flutter_firebase
description: A new Flutter project.
publish_to: 'none'
version: 1.12.5+44

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.5.0
  firebase_storage: ^12.4.1
  fluttertoast: ^9.0.0
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.2.1
  change_app_package_name: ^1.5.0
  curved_navigation_bar: ^1.0.6
  salomon_bottom_bar: ^3.3.2
  cached_network_image: ^3.4.1 
  shared_preferences: ^2.3.5
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  intl: ^0.20.1
  http: ^1.3.0
  flutter_stripe: ^12.1.0
  image_picker: ^1.1.2
  google_maps_flutter: ^2.10.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  geocoding: ^4.0.0
  flutter_polyline_points: ^3.1.0
  googleapis_auth: ^2.0.0
  flutter_paypal_payment: ^1.0.8
  firebase_messaging: ^15.2.10
  share_plus: ^7.2.1
  flutter_facebook_auth: ^7.1.2
  url_launcher: ^6.3.1
  facebook_app_events: ^0.20.1
  flutter_local_notifications: ^19.5.0 
  qr_flutter: ^4.1.0
  flutter_speed_dial: ^7.0.0
  new_version_plus: ^0.1.1
  flutter_staggered_grid_view: ^0.7.0
  package_info_plus: ^8.3.1
  flutter_fortune_wheel: ^1.3.2
  animated_text_kit: ^4.2.3
  flutter_firebase_chat_core: ^1.6.8
  flutter_chat_ui: ^2.9.1
  flutter_chat_types: ^3.6.2
  animations: ^2.0.11
  open_filex: ^4.7.0
  file_picker: ^10.3.3
  responsive_framework: ^1.5.1
  flutter_staggered_animations: ^1.1.1
  audioplayers: ^6.5.1
  fl_chart: ^1.1.1
  printing: ^5.11.0
  pdf: ^3.10.4
  firebase_database: 11.3.10
  uuid: ^4.5.2
  animate_do: ^4.2.0
  youtube_player_iframe: ^5.2.1

dependency_overrides:
  image_picker_android: ^0.8.8+2
  file_picker: ^8.0.6
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 

flutter:
  uses-material-design: true
  assets:
    - assets/login.png
    - assets/inicio.jpg
    - assets/logo.png
    - assets/logo2.png
    - assets/hamburgesas.png
    - assets/fondo.png
    - assets/fondo.jpg
    - assets/dona.png
    - assets/pizza.png
    - assets/ramen.png
    - assets/pollo.png
    - assets/Buldak.png
    - assets/bubbletea.png
    - assets/dumpling.png
    - assets/ramune.png
    - assets/papas.png
    - assets/Solo.png
    - assets/bolsa.png
    - assets/paypal.png
    - assets/descuento.png
    - assets/AYUDA.png
    - assets/idely.jpg
    - assets/plix.jpg
    - assets/equipo.png
    - assets/Independiente.png
    - assets/tesoro.png
    - assets/murcielago.png
    - assets/boo.png
    - assets/fantasma.png
    - assets/canasta.png
    - assets/telarana.png
    - assets/mapa.png
    - assets/calabasa.png
    - assets/Muricielago.png
    - assets/muerte.png
    - assets/cancion.ogg
    - assets/1.jpeg
    - assets/2.jpeg
    - assets/3.jpeg